name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          ### -- Linux --
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.2.2"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.4.4"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.6.5"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.8.4"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.10.7" }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "9.0.2"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "9.2.5"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "9.4.4"  }
      fail-fast: false

    steps:
    # ----------------
    - name: "Dummy"
      run: |
        echo M1 ${{ matrix.ghc }}
    # ----------------
    - uses: actions/checkout@v2
    # ----------------
    - name: Install PAPI
      run: sudo apt-get install -y libpapi-dev
    # ----------------
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    # ----------------
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}--${{ github.Shah }}
    # ----------------
    - name: Versions
      run: |
        cabal -V
        ghc -V
    # ----------------
    - name: Make sdist
      run: |
        mkdir sdist
        cabal sdist -o sdist
    - name: Unpack
      run: |
        mkdir unpacked
        tar -C unpacked -xzf sdist/tasty-papi*.tar.gz
        cd unpacked
    # ----------------
    - name: cabal check
      run: |
        cabal -vnormal check
    # ----------------
    - name: Build
      run: |
        if [ "${{ matrix.skip-test  }}" == "" ]; then FLAG_TEST=--enable-test; fi
        cabal configure $FLAG_TEST $FLAG_BENCH
        cabal build all --write-ghc-environment-files=always
    # ----------------
    # We can't run tests because of insufficient permissions:
    # > Exception: PAPI call failed: -15
    #- name: Test
    #  run: |
    #    cabal test all
